name: v4.x checks

on:
  workflow_call:
    inputs:
      ref:
        description: 'The commit the workflow should check out'
        required: true
        default: ${{ github.sha }}
        type: string

jobs:
  test-node:
    name: Node Test Specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Restore ~/.npm/ cache
      uses: actions/cache@v4
      with:
        path: ~/.npm # this is the cache where npm installs from before going out to the network
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
    - name: Restore dist/ cache
      uses: actions/cache@v4
      with:
        path: ./dist
        key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'rollup.config.js', 'src/*.js') }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --prefer-offline
    - run: make test-node

  test-browser:
    name: Browser Test Specs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Restore ~/.npm/ cache
      uses: actions/cache@v4
      with:
        path: ~/.npm # this is the cache where npm installs from before going out to the network
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
    - name: Restore dist/ cache
      uses: actions/cache@v4
      with:
        path: ./dist
        key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'rollup.config.js', 'src/*.js') }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --prefer-offline
    - run: make test-browser

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Restore ~/.npm/ cache
      uses: actions/cache@v4
      with:
        path: ~/.npm # this is the cache where npm installs from before going out to the network
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
    - name: Restore dist/ cache
      uses: actions/cache@v4
      with:
        path: ./dist
        key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'rollup.config.js', 'src/*.js') }}
    - run: npm install --prefer-offline
    - run: make lint

  typecheck:
    name: Types
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Restore ~/.npm/ cache
      uses: actions/cache@v4
      with:
        path: ~/.npm # this is the cache where npm installs from before going out to the network
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
    - name: Restore dist/ cache
      uses: actions/cache@v4
      with:
        path: ./dist
        key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'rollup.config.js', 'src/*.js') }}
    - run: npm install --prefer-offline
    - run: make typecheck
